# Generated by Django 3.1 on 2021-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210415_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('slug',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(default='Kyrgyzstan', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.CharField(default='Dinara', max_length=200),
        ),
    ]
