# Generated by Django 3.1 on 2021-04-21 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_product_watched'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeRateFavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('in_bookmarks', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs', to='main.product')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProductRelation',
        ),
        migrations.AlterField(
            model_name='product',
            name='watched',
            field=models.ManyToManyField(related_name='products', through='main.LikeRateFavor', to=settings.AUTH_USER_MODEL),
        ),
    ]
